### PR TITLE
Fix initialisation method for DummyVisionSystem

### PR DESCRIPTION
**Pull request by mundya**
Seemed to have not been updated in line with the normal vision system.

### CODE REVIEW

**Comment by mundya** [comment]
There are more problems with the dummy vision system but I don't really know the code well enough to fix them. For example, I keep getting the traceback: [stderr.txt](https://github.com/xchoo/spaun2.0/files/606867/stderr.txt) ... would someone be able to take a look at this please?

**Comment by xchoo** [comment]
Oopa. Thanks for pointing it out. 
I think I've fixed it. Will commit once the test run has completed. :)

**Comment by mundya** [comment]
Thanks! I'll get playing with Spaun on SpiNNaker once that's done.

Hope your writing is going well!

**Comment by xchoo** [comment]
Alrighty. I just pushed the fixes. Can you check if it works? 😄

**Comment by mundya** [comment]
Yep, with the dummy vision system I can get to build with reference Nengo, thank you. I will now revert to the world of SpiNNaker :smile:

**Pull request closed without merging**
