### PR TITLE
Fixes for Python 3 and installation.

### PR DESCRIPTION
**Pull request by jgosmann**
These changes allow Spaun to be run with Python 3 by
- making relative imports explicit
- using function style `print`
- explicitly converting things to lists where Python 3 returns
  iterators

Furthermore, this fixes some paths so that Spaun can be installed as a Python package, but this commit does not include a setup.py to do so. (My [ctn-archive/gosmann-frontiers2016](https://github.com/ctn-archive/gosmann-frontiers2016) will include a setup.py which could be adopted. That file is a tiny bit more complicated because Spaun is pulled in as a git submodule and I have to do some `package_dir` foo.)

This is the minimal set of changes that were required. Certain configurations might require more changes.

Note: I haven't tested whether this produces still the appropriate results. I'm only interested in the run time for benchmarking.

### CODE REVIEW

**Comment by xchoo** [comment]
Hmm. Sweet. I'll test and merge when I'm done the thesis. 😄

**Comment by xchoo** [comment]
You might have to remind me in a month to do this 😆

**Comment by jgosmann** [comment]
That's fine. Take your time. Just wanted to make the changes visible if anyone looks for it.

**Comment by xchoo** [comment]
These changes should now be live in the v2.0 release.

**Pull request closed without merging**
